###########################
#       DoorsReloaded     #
###########################

# written by mfnalex / JEFF Media GbR

# Settings for the knocking sound
# See here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound-knock-iron: ENTITY_ZOMBIE_ATTACK_IRON_DOOR
sound-knock-wood: ITEM_SHIELD_BLOCK
# A volume of 1.0 means 16 blocks, 2.0 means 32 blocks, etc.
sound-knock-volume: 1.0
sound-knock-pitch: 1.0
# See here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/SoundCategory.html
sound-knock-category: BLOCKS
